stack: matti/kontena-supervisor
version: 0.0.2
description: kontena-supervisor

expose: web

variables:
  KONTENA_LB_VIRTUAL_HOSTS:
    # BUG only_if: link_lb
    type: string
    # BUG required: false
    default: example.net
    from:
      prompt: KONTENA_LB_VIRTUAL_HOSTS

services:
  web:
    image: mattipaksula/kontena-supervisor
    deploy:
      strategy: daemon
      wait_for_port: 80
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_VIRTUAL_HOSTS={{ KONTENA_LB_VIRTUAL_HOSTS }}
    links:
      - lb-ingress/lb
