stack: matti/base
version: 0.0.1
description: base
expose: web

variables:
  image_web:
    type: string
    default: user/image:0.0.1
    from:
      prompt:
  affinity_web:
    type: string
    default: label!=no-base-web
    from:
      prompt:
  deploy_strategy_web:
    type: string
    default: ha
    from:
      prompt:
  instances_web:
    only_if:
      - deploy_strategy_web: ha
    type: integer
    default: 1
    from:
      prompt:
  internal_port_web:
    type: integer
    default: 8000
  some_secret:
    type: string
    from:
      vault: "${STACK}_some_secret"
      random_string: 48
    to:
      vault: "${STACK}_some_secret"
  link_lb:
    type: boolean
    default: true
    from:
      prompt:
  linked_lb:
    only_if: link_lb
    type: string
    default: lb-ingress/lb
    from:
      prompt: Linked loadbalancer
  lb_domain:
    only_if: link_lb
    type: string
    default: base.example.net
    from:
      prompt:

services:
  web:
    image: {{ image_web }}
    affinity:
      - {{ affinity_web }}
    stateful: true
    instances: {{ instances_web }}
    deploy:
      strategy: ha
      wait_for_port: {{ internal_port_web }}
      interval: 1d
    volumes:
      - /data
    environment:
    # {% if link_lb %}
      - KONTENA_LB_INTERNAL_PORT={{ internal_port_web }}
      - KONTENA_LB_VIRTUAL_HOSTS={{ lb_domain }}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
    # {% endif %}
    health_check:
      protocol: http
      port: {{ internal_port_web }}
      uri: /
      interval: 60
      initial_delay: 60
      timeout: 2
    hooks:
      post_start:
        - cmd: /entrypoint.sh upgrade --noinput || /entrypoint.sh upgrade --noinput
          name: migrations
          instances: 1
          oneshot: true
    links:
    # {% if link_lb %}
      - {{ linked_lb }}
    # {% endif %}
    depends_on:
      - something
