stack: matti/gogs
version: 0.1.0
description: gogs
expose: gogs
variables:
  affinity:
    type: string
    default: label!=no-gogs
    from:
      prompt:
  image:
    type: string
    default: gogs/gogs:latest
    from:
      prompt:
  linked_lb:
    type: string
    default: lb-ingress/lb
    from:
      prompt: Linked loadbalancer
  lb_domain:
    type: string
    default: gogs.example.net
    from:
      prompt:
  ssh_port:
    type: integer
    default: 2222
    from:
      prompt:

services:
  gogs:
    image: {{ image }}
    deploy:
      wait_for_port: 3000
    stateful: true
    volumes:
      - /data
    affinity:
      - {{ affinity }}
    environment:
      - KONTENA_LB_INTERNAL_PORT=3000
      - KONTENA_LB_VIRTUAL_HOSTS={{ lb_domain }}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
    health_check:
      protocol: http
      port: 3000
      uri: /user/login
      interval: 60
      initial_delay: 60
      timeout: 2
    ports:
      - "{{ssh_port}}:22"
    links:
      - {{ linked_lb }}
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.1-alpine
    deploy:
      wait_for_port: 5432
    stateful: true
    volumes:
      - /var/lib/postgresql
    affinity:
      - {{ affinity }}
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - POSTGRES_DB=gogs
    health_check:
      protocol: tcp
      port: 5432
      interval: 60
      initial_delay: 60
      timeout: 2
